### ISSUE TITLE
Need to bind BcnProvider class methods in constructor

### ISSUE THREAD

**Issue by simontakouridis** [idena-network/idena-sdk-js#61]
https://github.com/idena-network/idena-sdk-js/blob/a3b28f6966d074f2331a22188f8deec19663e433/src/providers/bcnProvider.ts#L14

I was having difficulty accessing these methods in a different scope (because they reference this). So I had to use a hack e.g.: https://github.com/simontakouridis/idena-community-wallet/blob/f0a9cb13eeadb0f8af170ec0cb7b529d311dbc8b/src/core/idena.js#L15

I think the average dev might get stumped, so a better solution would be to bind the methods in the constructor e.g.:
e.g.
export class BcnProvider extends BaseProvider {
...
constructor(httpProvider: AxiosInstance) {
    super(httpProvider);

    this.buildTx = this.buildTx.bind(this);
    this.feePerGas = this.feePerGas.bind(this);
}

cc @ridenaio

**Comment by ridenaio** [comment]
Hi! I think average dev uses simple call like `await  provider.Blockchain.feePerGas()`. You are using redux-saga, this library has special overloads for `call` method to pass the context. You can find how to this [here](https://redux-saga.js.org/docs/api/#callcontext-fn-args).

**Comment by simontakouridis** [comment]
Thank you so much, call([context, fn]) works perfectly!
